server:
  port: 8088

spring:
  application:
    name: HCMU-server
  profiles:
    active: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
