server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/root?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Root123

  redis:
    host: localhost
    port: 6379
    password:

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packagesToScan: org.hcmu.hcmuserver.controller
  api-docs:
    enabled: true

knife4j:
  # 开启增强配置
  enable: true
  basic:
    enable: false
    # Basic认证用户名
    username: test
    # Basic认证密码
    password: 123

