
spring:
  application:
    name: HCMU-server
  profiles:
    active: dev
  datasource:
    #   hikari数据源配置，
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 10000
      maximum-pool-size: 20
      max-lifetime: 60000
      minimum-idle: 5

  #配置邮箱
  mail:
    host: smtp.126.com
    port: 465
    protocol: smtp
    username: admin@admin.com
    nickname: HCMU
    password: admin123
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
        debug: true #调试模式
    test-connection: false #启动项目时验证是否可以正确通信 默认为false


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
