spring:
  application:
    name: HCMU-server
  profiles:
    active: dev
  datasource:
    #   hikari数据源配置，
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 10000
      maximum-pool-size: 20
      max-lifetime: 60000
      minimum-idle: 5

  # 对应上述创建的路径

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
